nacos.config.server-addr=10.5.36.115:8848
nacos.config.namespace=2b70e6d1-a81b-40fb-ac35-66e93e09b6bf
##logStash\uFFFD\uFFFD\u05B7\uFFFD\uFFFD\u01E8\uFFFD\u01B5\uFFFDnacos\uFFFD\uFFFD\u02A7\u0427\uFFFD\uFFFD
path.logStash=logstash.sportxxxyp7.com:5662