nacos.config.server-addr=172.21.247.54:8848
nacos.config.namespace=9385a036-b48c-4dde-97d7-c5e1872f2852

##logStash��ַ��Ǩ�Ƶ�nacos��ʧЧx��
#path.logStash= 172.18.178.80:4560
path.logStash=logstash.sportxxxkd1.com:5662,logstash-2.sportxxxkd1.com:5662

logging.level.com.lucifer.springboot.cache.mapper=debug

