nacos.config.server-addr=10.5.17.171:8848
nacos.config.namespace=78b3feba-001d-4080-8408-5c65b23aaab2

##logStash地址（迁移到nacos不生效）
path.logStash=logstash.sportxxxwo8.com:5662,logstash-2.sportxxxwo8.com:5662