jdbc.driverClass=com.mysql.cj.jdbc.Driver
#dev
#jdbc.connectionURL=jdbc:mysql://172.18.178.210:6606/panda?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#jdbc.userId=devtyweb
#jdbc.password=38tmpEKnwnH5dLhv
#test
#jdbc.connectionURL=jdbc:mysql://172.18.178.26:6606/panda?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#jdbc.userId=testtyweb
#jdbc.password=oX4naiUkew}A3}55X
#\uFFFD\uFFFD\uFFFD\uFFFD
#jdbc.connectionURL=jdbc:mysql://47.240.11.178:41001/panda?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#jdbc.userId=root
#jdbc.password=eIEIBhe&5rsfiD#gu1tu8FNeX!54nG@$JOL

#\u672C\u5730
jdbc.connectionURL=jdbc:mysql://103.84.45.134:10930/panda?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
jdbc.userId=testtyweb
jdbc.password=oX4naiUkew}A3}55X
