main.workerId=21
server.port=18081
# 连接我们刚刚下好的启动了的zookeeper  ip换成你的Linux的ip即可
#dubbo当前应用的名字
dubbo.application.name=panda-dubbo-consumer
dubbo.protocol.name=dubbo
dubbo.protocol.port=20884
dubbo.registry.protocol=zookeeper
#dev
dubbo.registry.address=172.18.178.191:2181,172.18.178.192:2181,172.18.178.193:2181
#test
#dubbo.registry.address=172.18.178.235:2181,172.18.178.236:2181,172.18.178.237:2181
#记住timeout一定要加进去不然会报错
dubbo.registry.timeout=10000
#开启参数校验
dubbo.provider.validation=true
#超时后,重试次数(retries)
dubbo.consumer.retries=3
#启动时检查(check),关闭所有服务的启动时检查@Reference(check = false)
dubbo.consumer.check=false



