package com.panda.merge.constant;


public class CacheConstant {
    public static final String FOOTBALL_STANDARD_MATCH_SCORES ="FOOTBALL_STANDARD_MATCH_SCORES:";
    /**
     * BC滚球赛事中途订阅,之前的统计比分不参与结算
     */
    public final static String BC_MATCH_EVENT_SUB_SWITCH_EVENT="BC_MATCH_EVENT_SUB_SWITCH_EVENT:";

    public final static String BC_ALL_PERIODS_SCORES_SEND="BC_ALL_PERIODS_SCORES_SEND:";

    public final static String STANDARD_MATCH_SCORES_HT = "STANDARD_MATCH_SCORES_HT:";

    public final static String STANDARD_MATCH_SCORES_2HT = "STANDARD_MATCH_SCORES_2HT:";


    //缓存篮球比分
    public final static String BASKETBALL_STANDARD_MATCH_SCORES = "BASKETBALL_STANDARD_MATCH_SCORES:";
    public final static String BASKETBALL_STANDARD_MATCH_SCORES_HT = "BASKETBALL_STANDARD_MATCH_SCORES_HT:";
    public final static String BASKETBALL_STANDARD_MATCH_SCORES_2HT = "BASKETBALL_STANDARD_MATCH_SCORES_2HT:";
    public final static String BASKETBALL_STANDARD_MATCH_SCORES_ALL = "BASKETBALL_STANDARD_MATCH_SCORES_ALL:";
    public final static String BASKETBALL_STANDARD_MATCH_SCORES_FIRST = "BASKETBALL_STANDARD_MATCH_SCORES_FIRST:";
    public final static String BASKETBALL_STANDARD_MATCH_SCORES_SECOND = "BASKETBALL_STANDARD_MATCH_SCORES_SECOND:";
    public final static String BASKETBALL_STANDARD_MATCH_SCORES_THIRD = "BASKETBALL_STANDARD_MATCH_SCORES_THIRD:";
    public final static String BASKETBALL_STANDARD_MATCH_SCORES_FOURTH = "BASKETBALL_STANDARD_MATCH_SCORES_FOURTH:";


}
