update language_internation set text = '斯諾克',modify_time = UNIX_TIMESTAMP() * 10000  where  language_type = 'zh' and name_code = 7;
update language_internation set text = '網球',modify_time = UNIX_TIMESTAMP() * 10000  where  language_type = 'zh' and name_code = 5;

#足球
update i18n_market_category set text = '全場獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '1' and sport_id = 1);
update i18n_market_category set text = '全場大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '2' and sport_id = 1);
update i18n_market_category set text = '全場讓球勝平負' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '3' and sport_id = 1);
update i18n_market_category set text = '全場讓球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '4' and sport_id = 1);
update i18n_market_category set text = '平局退款' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '5' and sport_id = 1);
update i18n_market_category set text = '雙重機會' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '6' and sport_id = 1);
update i18n_market_category set text = '全場比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '7' and sport_id = 1);
update i18n_market_category set text = '{$competitor1}準確進球數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '8' and sport_id = 1);
update i18n_market_category set text = '{$competitor2}準確進球數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '9' and sport_id = 1);
update i18n_market_category set text = '{$competitor1}進球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '10' and sport_id = 1);
update i18n_market_category set text = '{$competitor2}進球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '11' and sport_id = 1);
update i18n_market_category set text = '兩球都進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '12' and sport_id = 1);
update i18n_market_category set text = '獨贏 ＆ 進球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '13' and sport_id = 1);
update i18n_market_category set text = '準確進球數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '14' and sport_id = 1);
update i18n_market_category set text = '進球單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '15' and sport_id = 1);
update i18n_market_category set text = '最多進球的半場' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '16' and sport_id = 1);
update i18n_market_category set text = '半場獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '17' and sport_id = 1);
update i18n_market_category set text = '半場大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '18' and sport_id = 1);
update i18n_market_category set text = '半場讓球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '19' and sport_id = 1);
update i18n_market_category set text = '上半場比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '20' and sport_id = 1);
update i18n_market_category set text = '上半場{$competitor1}準確進球數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '21' and sport_id = 1);
update i18n_market_category set text = '上半場{$competitor2}準確進球數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '22' and sport_id = 1);
update i18n_market_category set text = '上半場準確進球數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '23' and sport_id = 1);
update i18n_market_category set text = '上半場兩隊都進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '24' and sport_id = 1);
update i18n_market_category set text = '下半場獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '25' and sport_id = 1);
update i18n_market_category set text = '下半場大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '26' and sport_id = 1);
update i18n_market_category set text = '剩餘時間獲勝' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '27' and sport_id = 1);
update i18n_market_category set text = '第{X}個進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '28' and sport_id = 1);
update i18n_market_category set text = '上半場剩餘時間獲勝' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '29' and sport_id = 1);
update i18n_market_category set text = '上半場第{X}個進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '30' and sport_id = 1);
update i18n_market_category set text = '第{X}個進球何時發生？' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '31' and sport_id = 1);
update i18n_market_category set text = '15分鐘進球-獨贏({a}-{b})' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '32' and sport_id = 1);
update i18n_market_category set text = '15分鐘進球-讓球({a}-{b})' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '33' and sport_id = 1);
update i18n_market_category set text = '15分鐘進球-大小({a}-{b})' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '34' and sport_id = 1);
update i18n_market_category set text = '首個進球球員' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '35' and sport_id = 1);
update i18n_market_category set text = '任意時間進球球員' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '36' and sport_id = 1);
update i18n_market_category set text = '上半場進球單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '42' and sport_id = 1);
update i18n_market_category set text = '上半場平局退款' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '43' and sport_id = 1);
update i18n_market_category set text = '總進球數區間' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '68' and sport_id = 1);
update i18n_market_category set text = '上半場讓球勝平負' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '69' and sport_id = 1);
update i18n_market_category set text = '上半場雙重機會' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '70' and sport_id = 1);
update i18n_market_category set text = '下半場讓球勝平負' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '71' and sport_id = 1);
update i18n_market_category set text = '下半場雙重機會' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '72' and sport_id = 1);
update i18n_market_category set text = '下半場準確進球數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '73' and sport_id = 1);
update i18n_market_category set text = '下半場比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '74' and sport_id = 1);
update i18n_market_category set text = '下半場進球單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '75' and sport_id = 1);
update i18n_market_category set text = '下半場兩隊都進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '76' and sport_id = 1);
update i18n_market_category set text = '{$competitor1}獲勝退款' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '77' and sport_id = 1);
update i18n_market_category set text = '{$competitor1}進球單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '78' and sport_id = 1);
update i18n_market_category set text = '{$competitor2}零失球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '79' and sport_id = 1);
update i18n_market_category set text = '{$competitor2}零失球獲勝' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '80' and sport_id = 1);
update i18n_market_category set text = '{$competitor1}零失球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '81' and sport_id = 1);
update i18n_market_category set text = '{$competitor1}零失球獲勝' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '82' and sport_id = 1);
update i18n_market_category set text = '{$competitor1}上/下半場全勝' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '83' and sport_id = 1);
update i18n_market_category set text = '{$competitor1}任意半場獲勝' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '84' and sport_id = 1);
update i18n_market_category set text = '{$competitor1}最高得分半場' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '85' and sport_id = 1);
update i18n_market_category set text = '{$competitor1}上/下半場均進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '86' and sport_id = 1);
update i18n_market_category set text = '上半場{$competitor1}進球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '87' and sport_id = 1);
update i18n_market_category set text = '下半場{$competitor1}進球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '88' and sport_id = 1);
update i18n_market_category set text = '下半場{$competitor1}零失球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '89' and sport_id = 1);
update i18n_market_category set text = '上半場{$competitor1}零失球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '90' and sport_id = 1);
update i18n_market_category set text = '{$competitor2}獲勝退款' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '91' and sport_id = 1);
update i18n_market_category set text = '{$competitor2}進球單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '92' and sport_id = 1);
update i18n_market_category set text = '{$competitor2}上/下半場全勝' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '93' and sport_id = 1);
update i18n_market_category set text = '{$competitor2}任意半場獲勝' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '94' and sport_id = 1);
update i18n_market_category set text = '{$competitor2}最高得分半場' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '95' and sport_id = 1);
update i18n_market_category set text = '{$competitor2}上/下半場均進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '96' and sport_id = 1);
update i18n_market_category set text = '上半場{{$competitor2}進球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '97' and sport_id = 1);
update i18n_market_category set text = '下半場{$competitor2}進球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '98' and sport_id = 1);
update i18n_market_category set text = '下半場{$competitor2}零失球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '99' and sport_id = 1);
update i18n_market_category set text = '上半場{$competitor2}零失球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '100' and sport_id = 1);
update i18n_market_category set text = '獨贏 ＆ 兩隊都進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '101' and sport_id = 1);
update i18n_market_category set text = '進球大小 ＆ 兩隊都進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '102' and sport_id = 1);
update i18n_market_category set text = '半/全場比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '103' and sport_id = 1);
update i18n_market_category set text = '半/全場' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '104' and sport_id = 1);
update i18n_market_category set text = '上半場獨贏 ＆ 上半場兩隊都進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '105' and sport_id = 1);
update i18n_market_category set text = '下半場獨贏 ＆ 下半場兩隊都進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '106' and sport_id = 1);
update i18n_market_category set text = '雙重機會 ＆ 兩隊都進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '107' and sport_id = 1);
update i18n_market_category set text = '上/下半場兩隊都進球' where  language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '108' and sport_id = 1);
update i18n_market_category set text = '上/下半場進球數均大於{X.5}' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '109' and sport_id = 1);
update i18n_market_category set text = '上/下半場進球數均小於{X.5}' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '110' and sport_id = 1);
update i18n_market_category set text = '角球獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '111' and sport_id = 1);
update i18n_market_category set text = '最後一個角球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '112' and sport_id = 1);
update i18n_market_category set text = '角球讓球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '113' and sport_id = 1);
update i18n_market_category set text = '角球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '114' and sport_id = 1);
update i18n_market_category set text = '{$competitor1}角球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '115' and sport_id = 1);
update i18n_market_category set text = '{$competitor2}角球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '116' and sport_id = 1);
update i18n_market_category set text = '角球總數區間' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '117' and sport_id = 1);
update i18n_market_category set text = '角球單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '118' and sport_id = 1);
update i18n_market_category set text = '上半場角球獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '119' and sport_id = 1);
update i18n_market_category set text = '上半場第{X}個角球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '120' and sport_id = 1);
update i18n_market_category set text = '上半場角球讓球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '121' and sport_id = 1);
update i18n_market_category set text = '上半場角球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '122' and sport_id = 1);
update i18n_market_category set text = '上半場{$competitor1}角球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '123' and sport_id = 1);
update i18n_market_category set text = '上半場{$competitor2}角球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '124' and sport_id = 1);
update i18n_market_category set text = '誰先獲得{X}個角球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '125' and sport_id = 1);
update i18n_market_category set text = '加時賽-獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '126' and sport_id = 1);
update i18n_market_category set text = '加時賽-大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '127' and sport_id = 1);
update i18n_market_category set text = '加時賽-讓球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '128' and sport_id = 1);
update i18n_market_category set text = '加時賽-上半場獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '129' and sport_id = 1);
update i18n_market_category set text = '加時賽-上半場讓球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '130' and sport_id = 1);
update i18n_market_category set text = '是否進行點球大戰' where anguage_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '131' and sport_id = 1);
update i18n_market_category set text = '點球大戰-獲勝者' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '132' and sport_id = 1);
update i18n_market_category set text = '點球大戰-第{X}個點球是否射進' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '133' and sport_id = 1);
update i18n_market_category set text = '點球大戰-大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '134' and sport_id = 1);
update i18n_market_category set text = '晉級球隊' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '135' and sport_id = 1);
update i18n_market_category set text = '冠軍' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '136' and sport_id = 1);
update i18n_market_category set text = '獲勝方式' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '137' and sport_id = 1);
update i18n_market_category set text = '比賽中出現紅牌' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '138' and sport_id = 1);
update i18n_market_category set text = '{$competitor1}獲得紅牌' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '139' and sport_id = 1);
update i18n_market_category set text = '{$competitor2}獲得紅牌' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '140' and sport_id = 1);
update i18n_market_category set text = '淨勝分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '141' and sport_id = 1);
update i18n_market_category set text = '下半場平局退款' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '142' and sport_id = 1);
update i18n_market_category set text = '下半場讓球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '143' and sport_id = 1);
update i18n_market_category set text = '誰先開球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '144' and sport_id = 1);
update i18n_market_category set text = '第{X}個進球球員' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '148' and sport_id = 1);
update i18n_market_category set text = '最後進球隊伍' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '149' and sport_id = 1);
update i18n_market_category set text = '最後進球球員' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '150' and sport_id = 1);
update i18n_market_category set text = '進2+球的球員' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '151' and sport_id = 1);
update i18n_market_category set text = '進3+球的球員' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '152' and sport_id = 1);
update i18n_market_category set text = '第{X}個進球方式' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '222' and sport_id = 1);
update i18n_market_category set text = '誰會進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '223' and sport_id = 1);
update i18n_market_category set text = '第{X}張罰牌' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '224' and sport_id = 1);
update i18n_market_category set text = '第{X}個角球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '225' and sport_id = 1);
update i18n_market_category set text = '{$competitor1}角球總數區間' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '226' and sport_id = 1);
update i18n_market_category set text = '{$competitor2}角球總數區間' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '227' and sport_id = 1);
update i18n_market_category set text = '上半場角球總數區間' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '228' and sport_id = 1);
update i18n_market_category set text = '上半場角球單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '229' and sport_id = 1);
update i18n_market_category set text = '上半場誰先獲得{X}個角球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '230' and sport_id = 1);
update i18n_market_category set text = '15分鐘角球-獨贏({a}-{b})' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '231' and sport_id = 1);
update i18n_market_category set text = '15分鐘角球-讓球({a}-{b})' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '232' and sport_id = 1);
update i18n_market_category set text = '15分鐘角球-大小({a}-{b})' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '233' and sport_id = 1);
update i18n_market_category set text = '加時賽是否進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '234' and sport_id = 1);
update i18n_market_category set text = '加時賽-第{X}個進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '235' and sport_id = 1);
update i18n_market_category set text = '加時賽-正確比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '236' and sport_id = 1);
update i18n_market_category set text = '點球大戰-第{X}個進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '237' and sport_id = 1);
update i18n_market_category set text = '點球大戰-淨勝分' where language_type = 'zh'  and name_code in(select name_code from standard_sport_market_category where market_category_id = '238' and sport_id = 1);
update i18n_market_category set text = '點球大戰-準確進球數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '239' and sport_id = 1);
update i18n_market_category set text = '點球大戰-單/雙' where language_type = 'zh'  and name_code in(select name_code from standard_sport_market_category where market_category_id = '240' and sport_id = 1);
update i18n_market_category set text = '點球大戰-正確比分' where  language_type = 'zh'  and name_code in(select name_code from standard_sport_market_category where market_category_id = '241' and sport_id = 1);
update i18n_market_category set text = '全場讓球' where  language_type = 'zh'  and name_code in(select name_code from standard_sport_market_category where market_category_id = '269' and sport_id = 1);
update i18n_market_category set text = '半場讓球' where  language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '270' and sport_id = 1);
update i18n_market_category set text = '冠軍' where language_type = 'zh'  and name_code in(select name_code from standard_sport_market_category where market_category_id = '10001' and sport_id = 1);
update i18n_market_category set text = '墊底' where language_type = 'zh'  and name_code in(select name_code from standard_sport_market_category where market_category_id = '10002' and sport_id = 1);
update i18n_market_category set text = '前二' where language_type = 'zh'  and name_code in(select name_code from standard_sport_market_category where market_category_id = '10003' and sport_id = 1);
update i18n_market_category set text = '前四' where language_type = 'zh'  and name_code in(select name_code from standard_sport_market_category where market_category_id = '10004' and sport_id = 1);
update i18n_market_category set text = '前六' where language_type = 'zh'  and name_code in(select name_code from standard_sport_market_category where market_category_id = '10005' and sport_id = 1);
update i18n_market_category set text = '升級' where language_type = 'zh'  and name_code in(select name_code from standard_sport_market_category where market_category_id = '10006' and sport_id = 1);
update i18n_market_category set text = '降級' where language_type = 'zh'  and name_code in(select name_code from standard_sport_market_category where market_category_id = '10007' and sport_id = 1);
update i18n_market_category set text = '排名上半區' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '10008' and sport_id = 1);
update i18n_market_category set text = '排名下半區' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '10009' and sport_id = 1);
update i18n_market_category set text = '進球最多的球隊' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '10010' and sport_id = 1);
update i18n_market_category set text = '進球最少的球隊' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '10011' and sport_id = 1);
update i18n_market_category set text = '最佳射手' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '10012' and sport_id = 1);

#政治娱乐
update i18n_market_category set text = '下一任總理' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '10015' and sport_id = 18);
update i18n_market_category set text = '下一任總統' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '10016' and sport_id = 18);
update i18n_market_category set text = '獲勝黨派' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '10017' and sport_id = 18);

#羽毛球
update i18n_market_category set text = '獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '153' and sport_id = 10);
update i18n_market_category set text = '讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '172' and sport_id = 10);
update i18n_market_category set text = '總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '173' and sport_id = 10);
update i18n_market_category set text = '準確局數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '174' and sport_id = 10);
update i18n_market_category set text = '第{X}局獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '175' and sport_id = 10);
update i18n_market_category set text = '第{X}局讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '176' and sport_id = 10);
update i18n_market_category set text = '第{X}局總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '177' and sport_id = 10);
update i18n_market_category set text = '第{X}局單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '178' and sport_id = 10);
update i18n_market_category set text = '第{X}局第{Y}分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '179' and sport_id = 10);
update i18n_market_category set text = '第{X}局首先獲得{Y}分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '203' and sport_id = 10);
update i18n_market_category set text = '全場比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '204' and sport_id = 10);

#网球
update i18n_market_category set text = '獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '153' and sport_id = 5);
update i18n_market_category set text = '讓盤' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '154' and sport_id = 5);
update i18n_market_category set text = '讓局' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '155' and sport_id = 5);
update i18n_market_category set text = '總局數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '202' and sport_id = 5);
update i18n_market_category set text = '雙重賽果(第1盤/全場獨贏)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '161' and sport_id = 5);
update i18n_market_category set text = '總局數單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '160' and sport_id = 5);
update i18n_market_category set text = '準確盤數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '159' and sport_id = 5);
update i18n_market_category set text = '全場比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '204' and sport_id = 5);
update i18n_market_category set text = '{$competitor1}總局數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '156' and sport_id = 5);
update i18n_market_category set text = '{$competitor2}總局數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '157' and sport_id = 5);
update i18n_market_category set text = '出現搶七局' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '158' and sport_id = 5);
update i18n_market_category set text = '第{X}盤獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '162' and sport_id = 5);
update i18n_market_category set text = '第{X}盤讓局' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '163' and sport_id = 5);
update i18n_market_category set text = '第{X}盤總局數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '164' and sport_id = 5);
update i18n_market_category set text = '第{X}盤總局數單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '165' and sport_id = 5);
update i18n_market_category set text = '第{X}盤是否出現搶七局' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '208' and sport_id = 5);
update i18n_market_category set text = '第{X}盤正確比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '166' and sport_id = 5);
update i18n_market_category set text = '第{X}盤第{Y}局和第{Y}+1局誰獲勝多' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '167' and sport_id = 5);
update i18n_market_category set text = '第{X}盤第{Y}局獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '168' and sport_id = 5);
update i18n_market_category set text = '{主隊選手}贏得一盤' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '205' and sport_id = 5);
update i18n_market_category set text = '{客隊選手}贏得一盤' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '206' and sport_id = 5);
update i18n_market_category set text = '任意一盤未失一局獲勝' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '207' and sport_id = 5);
update i18n_market_category set text = '第{X}盤搶七局正確比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '170' and sport_id = 5);
update i18n_market_category set text = '獨贏 ＆ 總局數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '171' and sport_id = 5);
update i18n_market_category set text = '總盤數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '169' and sport_id = 5);

#斯诺克
update i18n_market_category set text = '全場勝平負' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '1' and sport_id = 7);
update i18n_market_category set text = '獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '153' and sport_id = 7);
update i18n_market_category set text = '比賽進入決勝局' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '180' and sport_id = 7);
update i18n_market_category set text = '讓局' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '181' and sport_id = 7);
update i18n_market_category set text = '總局數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '182' and sport_id = 7);
update i18n_market_category set text = '單雙局' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '183' and sport_id = 7);
update i18n_market_category set text = '第{X}局獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '184' and sport_id = 7);
update i18n_market_category set text = '第{X}局讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '185' and sport_id = 7);
update i18n_market_category set text = '第{X}局總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '186' and sport_id = 7);
update i18n_market_category set text = '第{X}局總分單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '187' and sport_id = 7);
update i18n_market_category set text = '第{X}局首先到達{Y}分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '188' and sport_id = 7);
update i18n_market_category set text = '第{X}局單桿得分最高的選手' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '189' and sport_id = 7);
update i18n_market_category set text = '第{X}局單桿最高分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '190' and sport_id = 7);
update i18n_market_category set text = '第{X}局單桿破百' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '191' and sport_id = 7);
update i18n_market_category set text = '第{X}局選手1單桿破百' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '192' and sport_id = 7);
update i18n_market_category set text = '第{X}局選手2單桿破百' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '193' and sport_id = 7);
update i18n_market_category set text = '第{X}局會不會有犯規' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '194' and sport_id = 7);
update i18n_market_category set text = '第{X}局第{Y}個進球的選手' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '195' and sport_id = 7);
update i18n_market_category set text = '第{X}局打進最後一球的選手' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '196' and sport_id = 7);
update i18n_market_category set text = '第{X}局最後得分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '197' and sport_id = 7);
update i18n_market_category set text = '全場比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '204' and sport_id = 7);

#乒乓球
update i18n_market_category set text = '獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '153' and sport_id = 8);
update i18n_market_category set text = '讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '172' and sport_id = 8);
update i18n_market_category set text = '總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '173' and sport_id = 8);
update i18n_market_category set text = '準確局數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '174' and sport_id = 8);
update i18n_market_category set text = '第{X}局獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '175' and sport_id = 8);
update i18n_market_category set text = '第{X}局讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '176' and sport_id = 8);
update i18n_market_category set text = '第{X}局總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '177' and sport_id = 8);
update i18n_market_category set text = '第{X}局單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '178' and sport_id = 8);
update i18n_market_category set text = '第{X}局第{Y}分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '179' and sport_id = 8);
update i18n_market_category set text = '第{X}局首先獲得{Y}分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '203' and sport_id = 8);
update i18n_market_category set text = '全場比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '204' and sport_id = 8);

#排球
update i18n_market_category set text = '獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '153' and sport_id = 9);
update i18n_market_category set text = '準確局數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '159' and sport_id = 9);
update i18n_market_category set text = '正確比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '204' and sport_id = 9);
update i18n_market_category set text = '第{X}局獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '162' and sport_id = 9);
update i18n_market_category set text = '讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '172' and sport_id = 9);
update i18n_market_category set text = '總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '173' and sport_id = 9);
update i18n_market_category set text = '第{X}局讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '253' and sport_id = 9);
update i18n_market_category set text = '第{X}局總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '254' and sport_id = 9);
update i18n_market_category set text = '第{X}局單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '255' and sport_id = 9);
update i18n_market_category set text = '第{X}局誰先獲得{Y}分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '256' and sport_id = 9);

#美足
update i18n_market_category set text = '半場獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '17' and sport_id = 6);
update i18n_market_category set text = '半場讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '19' and sport_id = 6);
update i18n_market_category set text = '半場總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '18' and sport_id = 6);
update i18n_market_category set text = '半場總分單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '42' and sport_id = 6);
update i18n_market_category set text = '全場獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '37' and sport_id = 6);
update i18n_market_category set text = '是否進行加時賽' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '41' and sport_id = 6);
update i18n_market_category set text = '全場讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '39' and sport_id = 6);
update i18n_market_category set text = '全場總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '38' and sport_id = 6);
update i18n_market_category set text = '{$competitor1}總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '198' and sport_id = 6);
update i18n_market_category set text = '{$competitor2}總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '199' and sport_id = 6);
update i18n_market_category set text = '總分單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '40' and sport_id = 6);

#篮球
update i18n_market_category set text = '全場勝平負(不含加時)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '1' and sport_id = 2);
update i18n_market_category set text = '總分(不含加時)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '2' and sport_id = 2);
update i18n_market_category set text = '讓分勝平負(不含加時)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '3' and sport_id = 2);
update i18n_market_category set text = '讓分(不含加時)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '4' and sport_id = 2);
update i18n_market_category set text = '全場獨贏(不含加時)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '5' and sport_id = 2);
update i18n_market_category set text = '{$competitor1}總分(不含加時)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '10' and sport_id = 2);
update i18n_market_category set text = '{$competitor2}總分(不含加時)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '11' and sport_id = 2);
update i18n_market_category set text = '總分單/雙(不含加時)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '15' and sport_id = 2);
update i18n_market_category set text = '上半場勝平負' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '17' and sport_id = 2);
update i18n_market_category set text = '上半場總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '18' and sport_id = 2);
update i18n_market_category set text = '上半場讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '19' and sport_id = 2);
update i18n_market_category set text = '下半場勝平負' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '25' and sport_id = 2);
update i18n_market_category set text = '下半場總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '26' and sport_id = 2);
update i18n_market_category set text = '全場獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '37' and sport_id = 2);
update i18n_market_category set text = '總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '38' and sport_id = 2);
update i18n_market_category set text = '讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '39' and sport_id = 2);
update i18n_market_category set text = '總分單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '40' and sport_id = 2);
update i18n_market_category set text = '是否進行加時賽' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '41' and sport_id = 2);
update i18n_market_category set text = '上半場總分單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '42' and sport_id = 2);
update i18n_market_category set text = '上半場獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '43' and sport_id = 2);
update i18n_market_category set text = '第1節勝平負' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '44' and sport_id = 2);
update i18n_market_category set text = '第1節總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '45' and sport_id = 2);
update i18n_market_category set text = '第1節讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '46' and sport_id = 2);
update i18n_market_category set text = '第1節總分單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '47' and sport_id = 2);
update i18n_market_category set text = '第1節獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '48' and sport_id = 2);
update i18n_market_category set text = '第1節淨勝分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '49' and sport_id = 2);
update i18n_market_category set text = '第2節勝平負' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '50' and sport_id = 2);
update i18n_market_category set text = '第2節總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '51' and sport_id = 2);
update i18n_market_category set text = '第2節讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '52' and sport_id = 2);
update i18n_market_category set text = '第2節總分單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '53' and sport_id = 2);
update i18n_market_category set text = '第2節獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '54' and sport_id = 2);
update i18n_market_category set text = '第2節淨勝分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '55' and sport_id = 2);
update i18n_market_category set text = '第3節勝平負' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '56' and sport_id = 2);
update i18n_market_category set text = '第3節總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '57' and sport_id = 2);
update i18n_market_category set text = '第3節讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '58' and sport_id = 2);
update i18n_market_category set text = '第3節總分單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '59' and sport_id = 2);
update i18n_market_category set text = '第3節獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '60' and sport_id = 2);
update i18n_market_category set text = '第3節淨勝分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '61' and sport_id = 2);
update i18n_market_category set text = '第4節勝平負' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '62' and sport_id = 2);
update i18n_market_category set text = '第4節總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '63' and sport_id = 2);
update i18n_market_category set text = '第4節讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '64' and sport_id = 2);
update i18n_market_category set text = '第4節總分單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '65' and sport_id = 2);
update i18n_market_category set text = '第4節獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '66' and sport_id = 2);
update i18n_market_category set text = '第4節淨勝分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '67' and sport_id = 2);
update i18n_market_category set text = '下半場總分單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '75' and sport_id = 2);
update i18n_market_category set text = '上半場{$competitor1}總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '87' and sport_id = 2);
update i18n_market_category set text = '下半場{$competitor1}總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '88' and sport_id = 2);
update i18n_market_category set text = '上半場{$competitor2}總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '97' and sport_id = 2);
update i18n_market_category set text = '下半場{$competitor2}總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '98' and sport_id = 2);
update i18n_market_category set text = '半/全場(不含加時)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '104' and sport_id = 2);
update i18n_market_category set text = '淨勝分(不含加時)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '141' and sport_id = 2);
update i18n_market_category set text = '下半場獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '142' and sport_id = 2);
update i18n_market_category set text = '下半場讓分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '143' and sport_id = 2);
update i18n_market_category set text = '第{X}節{$competitor1}總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '145' and sport_id = 2);
update i18n_market_category set text = '第{X}節{$competitor2}總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '146' and sport_id = 2);
update i18n_market_category set text = '第{X}節首先獲得{Y}分(三項)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '147' and sport_id = 2);
update i18n_market_category set text = '{$competitor1}總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '198' and sport_id = 2);
update i18n_market_category set text = '{$competitor2}}總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '199' and sport_id = 2);
update i18n_market_category set text = '淨勝分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '200' and sport_id = 2);
update i18n_market_category set text = '首先獲得{Y}分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '201' and sport_id = 2);
update i18n_market_category set text = '淨勝分 6項' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '209' and sport_id = 2);
update i18n_market_category set text = '淨勝分 7項' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '210' and sport_id = 2);
update i18n_market_category set text = '淨勝分 12項' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '211' and sport_id = 2);
update i18n_market_category set text = '淨勝分 14項' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '212' and sport_id = 2);
update i18n_market_category set text = '最高得分的小節' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '213' and sport_id = 2);
update i18n_market_category set text = '誰先獲得第{X}分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '214' and sport_id = 2);
update i18n_market_category set text = '第{X}節首先獲得{Y}分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '215' and sport_id = 2);
update i18n_market_category set text = '獨贏 & 總分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '216' and sport_id = 2);
update i18n_market_category set text = '準確總分大小(不含加時)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '217' and sport_id = 2);
update i18n_market_category set text = '總分區間(不含加時)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '218' and sport_id = 2);
update i18n_market_category set text = '上半場淨勝分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '219' and sport_id = 2);
update i18n_market_category set text = '球員得分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '220' and sport_id = 2);
update i18n_market_category set text = '球員三分球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '221' and sport_id = 2);
update i18n_market_category set text = '球員助攻' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '271' and sport_id = 2);
update i18n_market_category set text = '球員籃板' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '272' and sport_id = 2);
update i18n_market_category set text = '冠軍' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '10001' and sport_id = 2);
update i18n_market_category set text = '最有價值球員' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '10013' and sport_id = 2);
update i18n_market_category set text = '決賽對陣球隊' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '10014' and sport_id = 2);

#冰球
update i18n_market_category set text = '全場勝平負' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '1' and sport_id = 4);
update i18n_market_category set text = '第{X}個進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '28' and sport_id = 4);
update i18n_market_category set text = '最後一個進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '149' and sport_id = 4);
update i18n_market_category set text = '雙重機會' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '6' and sport_id = 4);
update i18n_market_category set text = '平局退款' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '5' and sport_id = 4);
update i18n_market_category set text = '全場讓球勝平負' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '3' and sport_id = 4);
update i18n_market_category set text = '讓球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '4' and sport_id = 4);
update i18n_market_category set text = '大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '2' and sport_id = 4);
update i18n_market_category set text = '{$competitor1}進球大小(含加時點球大戰)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '257' and sport_id = 4);
update i18n_market_category set text = '{$competitor2}進球大小(含加時點球大戰)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '258' and sport_id = 4);
update i18n_market_category set text = '準確進球數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '14' and sport_id = 4);
update i18n_market_category set text = '{$competitor1}準確進球數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '8' and sport_id = 4);
update i18n_market_category set text = '{$competitor2}準確進球數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '9' and sport_id = 4);
update i18n_market_category set text = '進球單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '15' and sport_id = 4);
update i18n_market_category set text = '兩隊都進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '12' and sport_id = 4);
update i18n_market_category set text = '正確比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '204' and sport_id = 4);
update i18n_market_category set text = '全場獨贏(含加時點球大戰)' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '259' and sport_id = 4);
update i18n_market_category set text = '正確比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '260' and sport_id = 4);
update i18n_market_category set text = '第{X}節勝平負' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '261' and sport_id = 4);
update i18n_market_category set text = '第{X}節大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '262' and sport_id = 4);
update i18n_market_category set text = '第{X}節{$competitor1}進球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '263' and sport_id = 4);
update i18n_market_category set text = '第{X}節{$competitor2}進球大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '264' and sport_id = 4);
update i18n_market_category set text = '第{X}節準確進球數' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '265' and sport_id = 4);
update i18n_market_category set text = '第{X}節兩隊都進球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '266' and sport_id = 4);
update i18n_market_category set text = '第{X}節正確比分' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '267' and sport_id = 4);
update i18n_market_category set text = '第{X}節讓球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '268' and sport_id = 4);

#棒球
update i18n_market_category set text = '獨贏' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '242' and sport_id = 3);
update i18n_market_category set text = '讓球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '243' and sport_id = 3);
update i18n_market_category set text = '大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '244' and sport_id = 3);
update i18n_market_category set text = '{$competitor1} 得分大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '245' and sport_id = 3);
update i18n_market_category set text = '{$competitor2} 得分大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '246' and sport_id = 3);
update i18n_market_category set text = '得分單/雙' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '247' and sport_id = 3);
update i18n_market_category set text = '是否加時' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '248' and sport_id = 3);
update i18n_market_category set text = '前5局讓球' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '249' and sport_id = 3);
update i18n_market_category set text = '前5局大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '250' and sport_id = 3);
update i18n_market_category set text = '前5局主隊得分大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '251' and sport_id = 3);
update i18n_market_category set text = '前5局客隊得分大小' where language_type = 'zh' and name_code in(select name_code from standard_sport_market_category where market_category_id = '252' and sport_id = 3);

update standard_market_category set modify_time = UNIX_TIMESTAMP()*1000;
