update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Quốc tế' where id = 1;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Châu Á' where id = 2;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Châu Âu' where id = 3;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bắc Mỹ' where id = 4;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Nam Mỹ' where id = 5;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Châu Phi' where id = 6;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Châu Đại Dương' where id = 7;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Trung Quốc' where id = 8;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Sri Lanka' where id = 11;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Cộng hòa Serbia' where id = 12;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Cộng hoà Síp' where id = 13;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Cộng hòa Dominica' where id = 14;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Liên minh điện tử' where id = 15;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Mông Cổ' where id = 16;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bhutan' where id = 17;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Crimea' where id = 18;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Iceland' where id = 19;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bóng đá ảo' where id = 20;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Hungary' where id = 21;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Mexico' where id = 23;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bắc Ireland' where id = 24;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Xứ Wales' where id = 25;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Malta' where id = 26;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Vương quốc Brunei' where id = 27;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Cuba' where id = 28;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Brazil' where id = 29;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Grenada' where id = 30;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'New Zealand' where id = 31;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Croatia' where id = 32;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Benin' where id = 33;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Serbia' where id = 34;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Dominica' where id = 35;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Guadeloupe' where id = 36;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bosnia và Herzegovina' where id = 38;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Macedonia' where id = 39;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Lithuania' where id = 40;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Latvia' where id = 41;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Ecuador' where id = 42;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Saint Kitts và Nevis' where id = 43;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bắc Síp' where id = 44;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Đông Timor' where id = 45;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Austria' where id = 46;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Cộng hòa Séc' where id = 47;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Luxembourg' where id = 48;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Phần Lan' where id = 49;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Anh' where id = 50;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Quần đảo Faroe' where id = 51;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Peru' where id = 53;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Nga' where id = 54;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Scotland' where id = 55;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Slovakia' where id = 56;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Slovenia' where id = 57;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Albania' where id = 60;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Thụy Sĩ' where id = 61;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Mỹ' where id = 62;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Georgia' where id = 63;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Colombia' where id = 64;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Kazakhstan' where id = 65;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Moldova' where id = 66;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Paraguay' where id = 67;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Venezuela' where id = 68;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Costa Rica' where id = 69;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Hàn Quốc' where id = 70;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Armenia' where id = 71;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Azerbaijan' where id = 72;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Các Tiểu Vương Quốc Ả Rập Thống Nhất' where id = 73;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Iran' where id = 74;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Maroc' where id = 75;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Algeria' where id = 76;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Ai Cập' where id = 77;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Đức' where id = 78;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Saudi Arabia' where id = 79;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Ý' where id = 80;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Nam Phi' where id = 81;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Jordan' where id = 82;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Tây Ban Nha' where id = 83;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Kuwait' where id = 84;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Hồng Kông' where id = 85;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bỉ' where id = 86;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Australia' where id = 87;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bahrain' where id = 88;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Ấn Độ' where id = 89;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Qatar' where id = 90;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Hà Lan' where id = 91;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Guatemala' where id = 92;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Việt Nam' where id = 93;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Salvador' where id = 94;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Indonesia' where id = 95;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Andorra' where id = 96;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Tunisia' where id = 97;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bolivia' where id = 98;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Syria' where id = 99;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Uzbekistan' where id = 100;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Montenegro' where id = 101;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'San Marino' where id = 102;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Canada' where id = 103;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Nicaragua' where id = 104;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bờ biển Ngà' where id = 105;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Cameroon' where id = 106;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Quốc tế Thanh niên' where id = 107;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Câu lạc bộ quốc tế' where id = 108;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Oman' where id = 109;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Libya' where id = 110;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Lebanon' where id = 112;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Honduras' where id = 113;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Yemen' where id = 114;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bồ Đào Nha' where id = 115;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Singapore' where id = 116;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bangladesh' where id = 117;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Thổ Nhĩ Kỳ' where id = 118;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Sudan' where id = 119;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Ba Lan' where id = 120;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Thái Lan' where id = 121;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Argentina' where id = 122;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Iraq' where id = 123;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Chile' where id = 124;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Angola' where id = 126;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Jamaica' where id = 127;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Liechtenstein' where id = 128;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Ireland' where id = 129;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Belize' where id = 130;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Panama' where id = 131;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Trinidad và Tobago' where id = 132;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Nhật Bản' where id = 133;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Nigeria' where id = 134;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Palestine' where id = 135;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Ghana' where id = 136;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Namibia' where id = 137;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Kosovo' where id = 138;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Mauritania' where id = 139;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Puerto Rico' where id = 140;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Uruguay' where id = 141;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Cộng hòa Dân chủ Congo' where id = 142;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Na Uy' where id = 143;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Maldives' where id = 144;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Aruba' where id = 145;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Israel' where id = 146;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Hy Lạp' where id = 147;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bắc Triều Tiên' where id = 148;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Papua New Guinea' where id = 149;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Pakistan' where id = 150;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Macao' where id = 151;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Romania' where id = 152;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Kyrgyzstan' where id = 153;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bungari' where id = 154;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Myanmar' where id = 155;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Burkina Faso' where id = 156;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Barbados' where id = 157;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Đài Bắc Trung Hoa' where id = 158;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Guyana' where id = 159;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Haiti' where id = 160;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Pháp' where id = 161;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Giải đấu mô phỏng' where id = 162;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Tanzania' where id = 163;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Botswana' where id = 164;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Kenya' where id = 165;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Mozambique' where id = 166;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Fiji' where id = 167;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Zambia' where id = 168;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Zimbabwe' where id = 169;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Uganda' where id = 170;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Tajikistan' where id = 171;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Curacao' where id = 172;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Malawi' where id = 173;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Mali' where id = 174;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Tahiti' where id = 175;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Philippines' where id = 176;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Lào' where id = 177;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Campuchia' where id = 178;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Malaysia' where id = 179;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Togo' where id = 180;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Turkmenistan' where id = 181;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Afghanistan' where id = 182;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Ukraina' where id = 183;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'New Caledonia' where id = 184;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Vanuatu' where id = 185;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Quần đảo Solomon' where id = 186;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Senegal' where id = 187;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Congo' where id = 188;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Đan Mạch' where id = 189;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Suriname' where id = 190;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Nepal' where id = 191;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Djibouti' where id = 192;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Gabon' where id = 193;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Guam' where id = 194;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bahamas' where id = 195;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Quần đảo Cayman' where id = 196;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bermuda' where id = 197;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Mauritius' where id = 198;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Ethiopia' where id = 199;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Swaziland' where id = 200;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Belarus' where id = 201;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Estonia' where id = 202;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Gibraltar' where id = 203;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Somalia' where id = 204;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Antigua và Barbuda' where id = 205;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Rwanda' where id = 207;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Chad' where id = 208;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Liberia' where id = 209;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Nam Sudan' where id = 210;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Đảo Zanzibar' where id = 211;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Burundi' where id = 212;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Gambia' where id = 213;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Guinea' where id = 214;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Seychelles' where id = 215;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Equatorial Guinea' where id = 217;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Madagascar' where id = 218;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Lesotho' where id = 219;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Sierra Leone' where id = 220;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Guinea-Bissau' where id = 221;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Comoros' where id = 222;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Sao Tome và Principe' where id = 223;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Niger' where id = 224;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Samoa' where id = 225;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Thụy Điển' where id = 227;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Châu Mỹ' where id = 228;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bóng rổ ảo' where id = 229;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Monaco' where id = 230;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Reunion' where id = 231;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bermuda' where id = 232;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Dota ' where id = 233;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'CS' where id = 234;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'LOL' where id = 235;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Cape Verde' where id = 236;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Benin' where id = 237;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'ITF Nam' where id = 238;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'WTA' where id = 239;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'ITF Nữ' where id = 240;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'ATP' where id = 241;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Trận đấu biểu diễn' where id = 242;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Davis Cup' where id = 243;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Curacao' where id = 244;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Guyane thuộc Pháp' where id = 245;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Saint Lucia' where id = 246;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Nam Tư' where id = 247;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Saint Vincent và Grenadines' where id = 248;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Đảo Norfolk' where id = 250;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Đảo Bouvet' where id = 251;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Saint-Martin' where id = 252;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Thử thách cho nữ' where id = 253;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Liên Xô' where id = 254;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Eritrea' where id = 255;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Quần đảo Malvinas' where id = 256;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Tonga' where id = 257;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Đảo Marshall' where id = 258;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Vương giả vinh diệu' where id = 259;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Greenland' where id = 260;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Trận thách đấu' where id = 261;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Khác' where id = 262;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Truyền kỳ' where id = 263;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Thanh thiếu niên ' where id = 264;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Xe lăn' where id = 265;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Giải trí' where id = 266;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Pg E-sports' where id = 267;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Dreamhack' where id = 268;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Quần đảo Turks và Caicos' where id = 269;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Quần đảo Bắc Mariana' where id = 270;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Giải trí Pvp' where id = 271;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'GrowUp E-sports' where id = 272;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Thế giới' where id = 273;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Anguilla' where id = 274;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = '23 Creative Vn' where id = 275;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = '4D' where id = 276;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Phục kích Esport' where id = 277;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Qcf' where id = 278;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Trò chơi hay nhất' where id = 279;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Đặt cược an toàn' where id = 280;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bfs' where id = 281;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Nổ' where id = 282;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bờ biển Ngà' where id = 284;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Ctrl bật mở' where id = 285;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Cyberwolves' where id = 286;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Elisa' where id = 288;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Froggedtv' where id = 289;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Người chơi game' where id = 290;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Câu lạc bộ người chơi' where id = 291;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Grunex' where id = 292;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Giải trí hot' where id = 293;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Thông lượng cao' where id = 294;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Hussar' where id = 295;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Ilusion Esports' where id = 296;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Qlash' where id = 297;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Jjb' where id = 298;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'La Liga' where id = 299;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Truyền thông trực tiếp' where id = 300;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bậc thầy Merkur' where id = 301;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Monaspa' where id = 302;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Giải trí Myi ' where id = 303;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Liên minh thần thoại' where id = 304;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Phi địa lý' where id = 305;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Hải dương' where id = 306;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Khu vui chơi' where id = 307;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Chế độ khẩn cấp' where id = 308;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Sazka' where id = 309;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Mô phỏng thực tế' where id = 310;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Liên minh mô phỏng thực tế' where id = 311;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Nữ giới mô phỏng thực tế' where id = 312;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Các loại giải đấu' where id = 315;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Vision Esports' where id = 316;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Game Voka' where id = 317;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Weibo' where id = 318;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Anh' where id = 319;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'CONCACAF' where id = 322;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Tour ITF' where id = 325;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'UEFA Euro 2020' where id = 327;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Barbados' where id = 328;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Grand Slam' where id = 329;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bóng rổ E-sport' where id = 330;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Bóng đá E-sport' where id = 331;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Thế vận hội Đông Nam Á' where id = 332;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Xếp hạng trận đấu' where id = 333;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Burundi' where id = 334;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Trận đấu mời' where id = 337;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Tour thách đấu' where id = 338;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Thể thao' where id = 339;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Chính trị' where id = 340;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Svalbard và Jan Mayen' where id = 343;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Đấu trường truyền hình trực tiếp' where id = 344;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'La Liga Pro' where id = 345;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Liên minh thể thao Gt' where id = 346;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Dreamhack' where id = 347;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Game hay AS' where id = 348;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Eredivisie' where id = 349;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Series thể thao toàn cầu EA' where id = 350;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Khác' where id = 351;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Đại chiến E-sport' where id = 352;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'FIFA' where id = 353;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'GFinity' where id = 354;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'ESL' where id = 355;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'PGL' where id = 356;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Series Pes Latino' where id = 357;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Trận thách đấu' where id = 358;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'NBA' where id = 359;
update standard_sport_region set  modify_time = UNIX_TIMESTAMP()*1000, introduction_vi = 'Test' where id = 360;