nacos.config.server-addr=10.105.25.61:8848
nacos.config.namespace=dae2db49-dc94-4b86-a68f-1cd69c2a8585

##logStash\uFFFD\uFFFD\u05B7\uFFFD\uFFFD\u01E8\uFFFD\u01B5\uFFFDnacos\uFFFD\uFFFD\uFFFD\uFFFD\u0427\uFFFD\uFFFD
path.logStash=10.5.20.118:4560
